# fly.toml app configuration file generated for unifi-mc on 2024-10-30T09:02:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = 'lhr'

[build]

[deploy]
  strategy = 'immediate'

[env]
  TZ = 'Etc/UTC'

[[mounts]]
  source = 'unifi_data'
  destination = '/config'
  initial_size = '1gb'

[[services]]
  internal_port = 8443
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
