command = """\
bash -c ' \
    mkdir -p /config/mongodb/db && \
    /usr/bin/mongod \
        --quiet \
        --port 27017 \
        --dbpath /config/mongodb/db \
'
"""

[restart]
strategy = "never"
backoff = "0s"
attempts = 0

[environment]
keep-env = true
